#!/bin/sh

# builds the native version
export testbuild=true
export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig/

make -f makefile_for_native_release
buildresult=$?
export testbuild=false

if [[ buildresult -eq 0 ]]; then
	echo -e "\n\e[32m   BUILD SUCCESS !\e[0m"
	echo -e "   TESTING...\n"
	../native_version/juxt_edit
else
	echo -e "\e[31m   BUILD FAILED, NOT TESTING"
fi